stages:
  - build

build:
  stage: build
  script:
    - mkdir -p themes
    - if [ ! -d themes/even ]; then git clone https://github.com/olOwOlo/hugo-theme-even themes/even; fi
    - hugo
    - rm -rf $HOME/zhouyequan.com
    - mv public $HOME/zhouyequan.com
